defaults:
  - wcte_defaults
  - engine: regression
  - override loss@tasks.train.loss: huber
  - _self_

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/direction_mu_run/


data:
  split_path: /home/zhihao/Data/WCTE_data_fixed/Splitting/split_list_mu.npz

model:
  num_output_channels: 3

tasks:
  train:
    optimizers:
      lr: 0.002
    loss:
      delta: 0.04
    data_loaders:
      train:
        pre_transforms: []
    epochs: 60

engine:
  target_key:
    - directions



