defaults:
  - wcte_defaults
  - engine: FCclassifier
  - _self_

model:
  num_output_channels: 2

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/FC_mu_${now:%Y-%m-%d_%H:%M:%S}/

data:
  dataset:
    h5file: /home/zhihao/Data/WCTE_data_fixed/FC_wcte_CDS_pgun_e-_3M_mu-_3M_0to1GeV_fixedFC.h5
  split_path: /home/zhihao/Data/WCTE_data_fixed/split_list_mu_FC.npz

tasks:
  train:
    epochs: 20