defaults:
  - wcte_defaults
  - engine: classifier
  - _self_

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/classification_run/

data:
  split_path: /home/zhihao/Data/WCTE_data_fixed/Splitting/split_list_classification.npz

tasks:
  train:
    optimizers:
      lr: 0.002
    epochs: 50


engine:
  label_set:
    - 1
    - 2