defaults:
  - wcte_defaults
  - engine: regression
  - override loss@tasks.train.loss: huber
  - _self_

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/position_e_run/


data:
  split_path: /home/zhihao/Data/WCTE_data_fixed/Splitting/split_list_e.npz

model:
  num_output_channels: 3

tasks:
  train:
    loss:
      delta: 6
    data_loaders:
      train:
        pre_transforms: []
    epochs: 40


engine:
  target_key:
    - positions


