defaults:
  - wcte_defaults
  - engine: regression
  - override loss@tasks.train.loss: huber
  - _self_

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/energy_mu_run/


data:
  split_path: /home/zhihao/Data/WCTE_data_fixed/split_list_mu.npz

model:
  num_output_channels: 1

tasks:
  train:
    epochs: 60
    loss:
      delta: 8


engine:
  target_key:
    - energies

