defaults:
  - wcte_defaults
  - engine: regression
  - override loss@tasks.train.loss: huber_momentum
  - _self_

hydra:
  run:
    dir: /home/zhihao/Data/WCTE_data_fixed/Output/energy_e_run/


data:
  split_path: /home/zhihao/Data/WCTE_data_fixed/Splitting/split_list_e.npz

model:
  num_output_channels: 1

tasks:
  train:
    epochs: 60


engine:
  target_key:
    - energies

